# Generated by Django 4.2.16 on 2024-09-04 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=240)),
                ('address_street', models.CharField(max_length=120)),
                ('address_extra', models.CharField(blank=True, max_length=360, null=True)),
                ('town_city', models.CharField(max_length=120)),
                ('country_state', models.CharField(max_length=240)),
                ('postcode', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('create_an_account', models.BooleanField(default=False)),
                ('account_password', models.CharField(max_length=128)),
                ('order_notes', models.CharField(blank=True, max_length=260, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('professions', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='employes/image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('short_info', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discreption', models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('SKU', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(100000000)])),
                ('size', models.CharField(blank=True, choices=[('XS', 'xs'), ('S', 's'), ('M', 'm'), ('XL', 'xl'), ('2XL', '2xl'), ('XXL', 'xxl'), ('3XL', '3xl'), ('4XL', '4xl')], max_length=3, null=True)),
                ('color', models.CharField(blank=True, choices=[('RED', 'red'), ('BLUE', 'blue'), ('GREEN', 'green'), ('YELLOW', 'yellow'), ('ORANGE', 'orange'), ('PURPLE', 'purple'), ('PINK', 'pink'), ('BLACK', 'black'), ('WHITE', 'oq'), ('GRAY', 'gray'), ('BROWN', 'brown')], max_length=6, null=True)),
                ('price_choice', models.CharField(blank=True, choices=[(5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (35, 35), (50, 50), (100, 100), (200, 200)], max_length=3, null=True)),
                ('review', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sale', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.checkout')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('remove', models.BooleanField(default=False)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.checkout')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
